name 'wirbelsturm-kafka'
version '1.0.1'
source 'https://github.com/miguno/puppet-kafka.git'
author 'Michael G. Noll'
license 'Apache License, Version 2.0'
summary      'Module for managing and configuring Kafka'
description  'Module for managing and configuring Kafka'
project_page 'https://github.com/miguno/puppet-kafka'
#DISABLED UNTIL PUBLISHED ON PUPPETFORGE#dependency 'miguno/puppet-limits'
#DISABLED UNTIL PUBLISHED ON PUPPETFORGE#dependency 'miguno/puppet-supervisor'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
